version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - stocktrader-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws
    command: npm run dev
    depends_on:
      - backend
    networks:
      - stocktrader-network

networks:
  stocktrader-network:
    driver: bridge

volumes:
  node_modules:
